# Windows Node Configuration:
# Ensure WinRM is enabled on the Windows machine.
# The ansible.windows collection is installed:
# ansible-galaxy collection install ansible.windows

---
- name: Automate IIS Self-Signed SSL with Ansible
  hosts: windows
  tasks:

    - name: Install IIS Web-Server role
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Generate a self-signed certificate
      ansible.windows.win_shell: |
        New-SelfSignedCertificate `
          -DnsName "example.com" `
          -CertStoreLocation "cert:\LocalMachine\My" `
          -NotAfter (Get-Date).AddYears(5)
      register: cert_result

    - name: Get thumbprint of the created certificate
      ansible.windows.win_shell: |
        (Get-ChildItem -Path Cert:\LocalMachine\My | Where-Object { $_.DnsNameList -contains 'example.com' }).Thumbprint
      register: cert_thumbprint

    - name: Bind the self-signed certificate to the IIS site
      ansible.windows.win_iis_webbinding:
        name: 'Default Web Site'
        protocol: https
        port: 443
        certificate_hash: "{{ cert_thumbprint.stdout }}"
        certificate_store_name: MY

    - name: Remove HTTP binding
      ansible.windows.win_iis_webbinding:
        name: 'Default Web Site'
        protocol: http
        port: 80
        state: absent
